# Generated by Django 2.2.28 on 2024-10-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
