# Generated by Django 2.2.28 on 2024-10-04 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patientrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientRecord',
        ),
    ]
